version = 5.1.0
archive_dir = /etc/letsencrypt/archive/cloud-testing.ddns.net
cert = /etc/letsencrypt/live/cloud-testing.ddns.net/cert.pem
privkey = /etc/letsencrypt/live/cloud-testing.ddns.net/privkey.pem
chain = /etc/letsencrypt/live/cloud-testing.ddns.net/chain.pem
fullchain = /etc/letsencrypt/live/cloud-testing.ddns.net/fullchain.pem
[renewalparams]
account = 5cdc73057bb5d4b5fec09b61561b8e45
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
cloud-testing.ddns.net = /var/www/certbot
